__all__ = ['base_unit',
           'ground_unit',
           'water_unit',
           'air_unit',
           'tank',
           'jeep',
           'superjeep',
           'anti_armour',
           'battleship',
           'carrier',
           'artillery',
           'fighter',
           'anti_air',
           'bomber',
           'transport',
           'pt_boat',
           'speed_power_up',
           'health_power_up',
           'attack_power_up']
           
unit_types = {}
